Repository kalviumcommunity/S70_Arav_Shreyas_Capstone_OpusSync, pull requests merged in 2025-06, with the labels that each got.

#30 added bruno folder with api endpoints
  OpusSync_Capstone/Member/Join Workspace.bru
  OpusSync_Capstone/Project/Create Project.bru
  OpusSync_Capstone/Project/Delete Project.bru
  OpusSync_Capstone/Project/Get All Projects.bru
  OpusSync_Capstone/Project/Project Analytics.bru
  OpusSync_Capstone/Project/Single Project.bru
  OpusSync_Capstone/Project/Update Project.bru
  OpusSync_Capstone/Project/folder.bru
  OpusSync_Capstone/Task/All Tasks.bru
  OpusSync_Capstone/Task/Create Task.bru
  OpusSync_Capstone/Task/Delete Task.bru
  OpusSync_Capstone/Task/Single Task.bru
  OpusSync_Capstone/Task/Update Task.bru
  OpusSync_Capstone/Task/folder.bru
  OpusSync_Capstone/Workspace/All Members.bru
  OpusSync_Capstone/Workspace/All User Worksapces.bru
  OpusSync_Capstone/Workspace/Change Member Role.bru
  OpusSync_Capstone/Workspace/Create Worksapce.bru
  OpusSync_Capstone/Workspace/Delete Workspace.bru
  OpusSync_Capstone/Workspace/Update Workspace.bru
  OpusSync_Capstone/Workspace/Workspace Analytics.bru
  OpusSync_Capstone/Workspace/Workspace by id.bru
  OpusSync_Capstone/Workspace/folder.bru
Labels: Review effort 2/5

#31 updated client and backend and implemented update and delete in react…
  OpusSync_Capstone/Auth/Register User.bru
  OpusSync_Capstone/Member/Get Current User.bru
  OpusSync_Capstone/Member/folder.bru
  OpusSync_Capstone/bruno.json
  backend/config/app.config.js
  backend/config/cloudinary.config.js
  backend/controllers/auth.controller.js
  backend/controllers/google-auth.controller.js
  backend/controllers/project.controller.js
  backend/controllers/user.controller.js
  backend/middlewares/isAuthenticated.middleware.js
  backend/models/user.model.js
  backend/routes/user.route.js
  backend/services/auth.service.js
  backend/services/project.service.js
  backend/services/user.service.js
  client/src/components/sidebar/Sidebar.jsx
  client/src/components/workspace/CreateWorkspaceDialog.jsx
  client/src/components/workspace/WorkspaceAnalytics.jsx
  client/src/components/workspace/member/RecentMembers.jsx
  client/src/components/workspace/project/CreateProjectDialog.jsx
  client/src/components/workspace/project/ProjectAnalytics.jsx
  client/src/components/workspace/project/RecentProjects.jsx
  client/src/components/workspace/project/custom-emojis.js
  client/src/components/workspace/task/CreateTaskDialog.jsx
  client/src/components/workspace/task/RecentTasks.jsx
  client/src/components/workspace/task/TaskDetailDisplay.jsx
  client/src/components/workspace/task/TaskTable.jsx
  client/src/context/auth-context.jsx
  client/src/main.jsx
  client/src/page/auth/GoogleOAuthSuccess.jsx
  client/src/page/auth/SignIn.jsx
  client/src/page/workspace/InviteJoinPage.jsx
  client/src/page/workspace/Members.jsx
  client/src/page/workspace/Projects.jsx
  client/src/page/workspace/Task.jsx
  client/src/page/workspace/UserProfileSettings.jsx
  client/src/page/workspace/WorkspaceDashboard.jsx
  client/src/page/workspace/WorkspaceSettings.jsx
  client/src/routes/routePaths.jsx
  client/src/setupAxios.js
Labels: Review effort 4/5

#32 implemented file upload to cloudinary
  client/.env
  client/.gitignore
  client/src/page/workspace/UserProfileSettings.jsx
Labels: Review effort 2/5

#37 Eshwar-to-Arav, VerifyPasswordOtpPage
  client/src/page/auth/VerifyPasswordOtpPage.jsx
Labels: Review effort 3/5

#38 Abhiram-to-Arav, ResetPasswordPage
  client/src/page/auth/ResetPasswordPage.jsx
Labels: Review effort 2/5
